### ISSUE TITLE
Include Links to some selected Youtube videos about JPEG compression to IM Examples/Usage documents section

### ISSUE THREAD

**Issue by pdfkungfoo** [ImageMagick/usage-markdown#1]
Quoting from a mail by Anthony Thyssen:

There is a great You Tube Video on the channel "Computerphile" that explains very clearly in good detail how JPEG Compression works. Specifically the last on in a series of four videos.
- The Problem with JPEG:  https://www.youtube.com/watch?v=yBX8GFqt6GA
- Colourspaces (JPEG Pt0):  https://www.youtube.com/watch?v=LFXN9PiOGtY
- JPEG 'files' & Color (JPEG Pt1):  https://www.youtube.com/watch?v=n_uNPbdenRs
- JPEG DCT, Discrete Cosine Transform (JPEG Pt2):  https://www.youtube.com/watch?v=Q2aEzeMDHMA

These links should be included in ImageMagick Examples.

**Comment by emcconville** [comment]
Updated JPEG Compression format with links
