### ISSUE TITLE
Update Thumbnails Rounded

### ISSUE THREAD

**Issue by emcconville** [ImageMagick/usage-markdown#17]
http://www.imagemagick.org/Usage/thumbnails/#rounded

Circle masked Image (example)...

Using a Polar Cycle Trick we can generate a perfect anti-aliased circle mask for any sized thumbnail. Of course we will only use the distorted image as a mask for the original image, so as to get the best result.

```
convert thumbnail.gif -alpha set \
             \( +clone -distort DePolar 0 \
            -virtual-pixel HorizontalTile -background None -distort Polar 0 \) \
            -compose Dst_In -composite -trim +repage circle_masked.png
```

**Comment by pdfkungfoo** [comment]
Eric, I'm not understanding this and/or its context. Can you help me out?

**Comment by emcconville** [comment]
Apologies @KurtPfeifle. This is a reference to [Anthony's post](http://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=28115). The thumbnail document will need to be updated to reflect HTML changes.

**Comment by emcconville** [comment]
Thumbnails updated
