### ISSUE TITLE
Update Sigmoidal Contrast Example and Links

### ISSUE THREAD

**Issue by MarkSetchell** [ImageMagick/usage-markdown#2]
Per Email from Anthony Thyssen, make updates suggested by Shriramana Sharma to examples on Sigmoidal Contrast.

**Comment by emcconville** [comment]
Applied equation from Shriramana's email from HTML source. Still need to review links, and additional comments.
<img width="765" alt="screen shot 2015-07-23 at 9 09 50 pm" src="https://cloud.githubusercontent.com/assets/84594/8866202/34461b82-317f-11e5-8ca6-2c3418ad0e0b.png">

**Comment by MarkSetchell** [comment]
Nice work!

**Comment by emcconville** [comment]
Closing this issue, unless I missed something from previous email. If so, please open new issue
