### ISSUE TITLE
[current tasks] Convert text prosa in all 'index.md' files according to "One sentence, one line" rule

### ISSUE THREAD

**Issue by pdfkungfoo** [ImageMagick/usage-markdown#3]
As was discussed by mail, we should convert all textual contents in our Markdown files according to the rule _"One sentence, one line."_  Text in between paragraphs remain, of course, separated by empty lines. The purpose of this is to create a better file format for future editing work, because it makes it easier to track changes and use text tools like `diff` in a more meaningful way.
1. Small typo fixes or other corrections can be applied to the texts at this stage too, even though it is not its main purpose.
2. All headlines should use _ATX_-style Markdown (that is, 1 or more `#`-characters to lead in the headline), and they should match the original HTML.
3. All `fenced_code_blocks` should work correctly (that is, when converting to HTML); they do no yet need to have their respective _attributes_ applied (since the details for these are still under investigation and discussion, and working on these will become a separate task once we are clear about the details).
4. To track who works on which file, please use the file `activities---one-sentence-one-line.md` and keep it current.

**Comment by emcconville** [comment]
These can be broken into separate issues, and a checklist can be created for activities. See [Document-Inventory-Template](https://github.com/IM6-Documentation/usage-markdown/wiki/Document-Inventory-Template)

Example: Issue #4

**Comment by emcconville** [comment]
Closings as complete, as the majority of the documents are now OSOL, ATX headers, and fixing minor spelling/grammer will continue past the scope of this ticket.
