### ISSUE TITLE
Separating paragraphs by empty lines

### ISSUE THREAD

**Issue by pdfkungfoo** [ImageMagick/usage-markdown#5]
Many paragraphs which were separate in Anthony's original HTML are now (accidentally) merged by the first automated/scripted conversion to Markdown.

This has to be fixed by adding empty lines between paragraphs (unless a case-by-case editorial decision by the one doing the work rules that the merge is in order for this case.)
## Status / Activity
- [x] advanced/index.md
- [x] anim_basics/index.md
- [x] anim_mods/index.md
- [x] anim_opt/index.md
- [x] annotating/index.md
- [x] antialiasing/index.md
- [x] api/index.md
- [x] backgrounds/index.md
- [x] basics/index.md
- [x] blur/index.md
- [x] bugs/animation_bgnd/index.md
- [x] bugs/blur_trans/index.md
- [x] bugs/composite_mask/index.md
- [x] bugs/displace/index.md
- [x] bugs/draw_percent/index.md
- [x] bugs/future/index.md
- [x] bugs/fuzz_distance/index.md
- [x] bugs/index.md
- [x] bugs/ordered-dither/index.md
- [x] bugs/quantization/index.md
- [x] bugs/resize_halo/index.md
- [x] bugs/testing/index.md
- [x] bugs/trans_bug/index.md
- [x] canvas/index.md
- [x] color_basics/index.md
- [x] color_mods/index.md
- [x] compare/index.md
- [x] compose/index.md
- [x] compose/tables/index.md
- [x] convolve/index.md
- [x] crop/index.md
- [x] distorts/affine/index.md
- [x] distorts/index.md
- [x] draw/index.md
- [x] files/index.md
- [x] filter/index.md
- [x] filter/nicolas/index.md
- [x] fonts/index.md
- [x] formats/index.md
- [x] fourier/fft_math/index.md
- [x] fourier/index.md
- [x] index.md
- [x] layers/index.md
- [x] lens/index.md
- [x] mapping/index.md
- [x] masking/index.md
- [x] misc/index.md
- [x] montage/index.md
- [x] morphology/index.md
- [x] photos/index.md
- [x] quantize/index.md
- [x] resize/index.md
- [x] text/index.md
- [x] thumbnails/index.md
- [x] transform/index.md
- [x] video/index.md
- [x] warping/index.md
- [x] windows/index.md

**Comment by emcconville** [comment]
Whitespace that was removed during batch conversion has been restored. Some elements (inline/block) may still exist, and a new issue should be opened if found.
