### ISSUE TITLE
Convert "bold" headings into proper ATX-style headers

### ISSUE THREAD

**Issue by pdfkungfoo** [ImageMagick/usage-markdown#7]
Sometimes there are short paragraphs or single lines with only a few words (not even a complete sentence) which clearly serve as a sort of headline.

Convert these into properly marked ATX headers (in most cases a header of 4th or 5th order would be appropriate).

**Comment by emcconville** [comment]
Closing this out, as I believe this is complete. The format/index.md was probably the most confusing of them all, so an extra pair of eyes should revisit that document.
